### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NourSoltani** [Angus-Toms/Triton#1]
Hello! I hope you are doing well.
It sounds great that you are working on floods. Are you referring here to the "Triton: A multi-GPU open source 2D hydrodynamic flood model" paper?

**Comment by Angus-Toms** [comment]
Hi Nour, 
This is a tool for conducting automated FCERM Economic Appraisals. However, this paper may warrant a change of name for this project!

**Comment by NourSoltani** [comment]
Oh OK. That's great! 
I wish you all the best.
